module.exports = {
  recents: 3,
  members: [
    { id: 'pjincz', nickname: '洗剪吹总监' },
    { id: 'cuiaoxiang', nickname: 'cuiaoxiang' },
    { id: 'QAMichaelPeng', nickname: 'Feng.P' },
    { id: 'IrisGuo', nickname: '烤小鸭' },
    { id: 'SeymourLee', nickname: 'SeymourLee' },
    { id: 'ws1255', nickname: '这个问题老大难' },
    { id: 'JackTheBest', nickname: '规则长方体固体物瞬间移动工程师' },
    { id: 'fish444556', nickname: 'Jialin' },
    { id: 'ZOEGREEN', nickname: 'sss' },
    { id: 'bifeitang', nickname: '蔽芾棠' },
    { id: 'Aaron_S', nickname: 'Aaron' },
    { id: 'lulinzhang1124', nickname: 'Lulin' },
    { id: 'whe_bupt', nickname: '旺旺' },
    { id: 'cookiecookie', nickname: '婷婷大熊猫' },
    { id: 'kaizer87', nickname: '🎶🎶🎶' },
    { id: 'huyouhyw', nickname: '忽悠' },
    { id: 'huange', nickname: '怪懒懒' },
    { id: 'keyupeter', nickname: '于可 Peter🚇' },
    { id: 'bellumpara', nickname: 'Drowning Fish' },
    { id: 'ForGive', nickname: 'Fan Liu' },
    { id: 'banrenmasanxing', nickname: '杨左使' },
    { id: 'yykfight', nickname: '俞盈克💪' },
    { id: 'liulaoye135', nickname: 'WorkHardSoMyCatCanHavABetterLife' },
    { id: 'siqiaochen', nickname: 'Philip' },
    { id: 'XYang93', nickname: '°' },
    { id: 'softair', nickname: '程川' },
    { id: 'OneDirection', nickname: 'Warmer' },
    { id: 'wyzhang421', nickname: 'Wanying Zhang' },
    { id: 'Mengqian', nickname: '米兰的小铁匠' },
    { id: 'xfzhao', nickname: 'edu' },
    { id: 'hfuwu5', nickname: 'Andrew' },
    { id: 'user4286', nickname: 'coo' },
    { id: 'jliang', nickname: '🐻' },
    { id: 'chanceliu', nickname: '刘畅斯 Chance' },
    { id: 'yexiaoxiao2102', nickname: '小叶叶叶叶叶叶' },
    { id: 'Coder35', nickname: '郑凯宇' },
    { id: 'fuxuemingzhu', nickname: '负雪明烛' },
    { id: 'Spencial', nickname: 'spencial' },
    { id: 'Charles000', nickname: '刷出一条蟹路来 :-)' },
    { id: 'sdliuyuzhi', nickname: '喜刷刷' },
    { id: 'Ansonluo1', nickname: 'Anson' },
    { id: 'icodingg', nickname: '暮鼓晨钟' },
    { id: 'zchen9523', nickname: '知知🥗🥗' },
    { id: 'discipline_', nickname: '舟' },
    { id: 'fyang618', nickname: '杨凡' },
    { id: 'ninjadq', nickname: 'DQ' },
    { id: 'zexingfa', nickname: 'Jersin🌟' },
    { id: 'XingxingHuang', nickname: '黄xing' },
    { id: 'Piterep', nickname: '彼得大帝' },
    { id: 'hgzry812', nickname: 'yuzi' },
    { id: 'wolf940509', nickname: '王瀚' },
    { id: 'xiaotang923', nickname: '璞员外' },
    { id: 'yishun', nickname: '一瞬' },
    { id: 'imaginationsuper', nickname: '🌈李世杰🆒🤠✨' },
    { id: 'porkgyro', nickname: '🐷肉卷' },
    { id: 'hy30305340', nickname: '🐬🐬🐬' },
    { id: 'tomdong05', nickname: '鞋子特大号' },
    { id: 'johnsysu', nickname: '陈风' },
    { id: 'wuweitong', nickname: '乌伟彤' },
    { id: 'sshang', nickname: 'SSQ' },
    { id: 'darrenfu', nickname: 'Darren' },
  ],
};

